import React, { useState, useEffect } from 'react';
import { orderService, shipmentService } from '../services/api';
import toast from 'react-hot-toast';
import { Edit2, Eye } from 'lucide-react';

export default function OrderManagement({ userRole }) {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [editingOrder, setEditingOrder] = useState(null);
  const [viewingTimeline, setViewingTimeline] = useState(null);
  const [shipmentData, setShipmentData] = useState({
    status: 'Confirmed',
    location: '',
    note: ''
  });

  useEffect(() => {
    fetchOrders();
  }, []);

  const fetchOrders = async () => {
    try {
      const { data } = await orderService.getAll();
      setOrders(data);
    } catch (error) {
      toast.error('Failed to load orders');
    } finally {
      setLoading(false);
    }
  };

  const handleEditOrder = (order) => {
    setEditingOrder(order);
    setShipmentData({
      status: order.status,
      location: '',
      note: ''
    });
  };

  const handleUpdateStatus = async (e) => {
    e.preventDefault();
    try {
      await orderService.updateStatus(editingOrder._id, shipmentData);
      toast.success('Order status updated successfully!');
      setEditingOrder(null);
      fetchOrders();
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to update order');
    }
  };

  const handleViewTimeline = async (orderId) => {
    try {
      const { data } = await shipmentService.getTimeline(orderId);
      setViewingTimeline(data);
    } catch (error) {
      toast.error('Failed to load shipment timeline');
    }
  };

  const getStatusColor = (status) => {
    const colors = {
      'Pending': 'badge-pending',
      'Confirmed': 'badge-info',
      'In-Transit': 'badge-info',
      'Out-for-Delivery': 'badge-pending',
      'Delivered': 'badge-success'
    };
    return colors[status] || 'badge-info';
  };

  if (loading) {
    return <div className="flex justify-center items-center h-96">Loading...</div>;
  }

  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold text-gray-800">
        {userRole === 'vendor' ? 'My Orders' : 'Order Management'}
      </h1>

      {/* Orders Table */}
      <div className="card">
        <div className="table-responsive">
          <table className="table">
            <thead>
              <tr className="bg-gray-50">
                <th>Drug</th>
                <th>Quantity</th>
                <th>Status</th>
                <th>Generated By</th>
                {userRole === 'vendor' && <th>Vendor</th>}
                <th>Created Date</th>
                {userRole === 'vendor' && <th>Actions</th>}
              </tr>
            </thead>
            <tbody>
              {orders.length > 0 ? (
                orders.map((order) => (
                  <tr key={order._id}>
                    <td className="font-medium">{order.drugId?.drugName || 'N/A'}</td>
                    <td>{order.quantity}</td>
                    <td><span className={`badge ${getStatusColor(order.status)}`}>{order.status}</span></td>
                    <td>{order.generatedBy?.name || 'N/A'}</td>
                    {userRole === 'vendor' && (
                      <td>{order.fulfilledBy?.companyName || 'Unassigned'}</td>
                    )}
                    <td>{new Date(order.createdAt).toLocaleDateString()}</td>
                    {userRole === 'vendor' && (
                      <td>
                        <div className="flex gap-2">
                          <button
                            onClick={() => handleViewTimeline(order._id)}
                            className="text-blue-600 hover:text-blue-800 transition"
                            title="View timeline"
                          >
                            <Eye size={18} />
                          </button>
                          <button
                            onClick={() => handleEditOrder(order)}
                            className="text-green-600 hover:text-green-800 transition"
                            title="Update status"
                          >
                            <Edit2 size={18} />
                          </button>
                        </div>
                      </td>
                    )}
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="7" className="text-center text-gray-500 py-8">No orders found</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Update Order Modal */}
      {editingOrder && userRole === 'vendor' && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="card max-w-md w-full mx-4">
            <h2 className="text-2xl font-bold mb-4">Update Order Status</h2>
            <div className="mb-4 p-3 bg-gray-50 rounded">
              <p className="text-sm text-gray-600">Drug: <strong>{editingOrder.drugId?.drugName}</strong></p>
              <p className="text-sm text-gray-600">Quantity: <strong>{editingOrder.quantity}</strong></p>
              <p className="text-sm text-gray-600">Current Status: <strong>{editingOrder.status}</strong></p>
            </div>

            <form onSubmit={handleUpdateStatus} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Status</label>
                <select
                  value={shipmentData.status}
                  onChange={(e) => setShipmentData({ ...shipmentData, status: e.target.value })}
                  className="input-field"
                >
                  <option value="Confirmed">Confirmed</option>
                  <option value="In-Transit">In-Transit</option>
                  <option value="Out-for-Delivery">Out-for-Delivery</option>
                  <option value="Delivered">Delivered</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Current Location</label>
                <input
                  type="text"
                  value={shipmentData.location}
                  onChange={(e) => setShipmentData({ ...shipmentData, location: e.target.value })}
                  placeholder="e.g., In warehouse, Route to hospital, etc."
                  className="input-field"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Update Notes</label>
                <textarea
                  value={shipmentData.note}
                  onChange={(e) => setShipmentData({ ...shipmentData, note: e.target.value })}
                  placeholder="Add any notes about the shipment..."
                  className="input-field h-24 resize-none"
                />
              </div>

              <div className="flex gap-2 pt-4">
                <button
                  type="submit"
                  className="btn-primary flex-1"
                >
                  Update Status
                </button>
                <button
                  type="button"
                  onClick={() => setEditingOrder(null)}
                  className="btn-secondary flex-1"
                >
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Shipment Timeline Modal */}
      {viewingTimeline && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="card max-w-2xl w-full mx-4 max-h-96 overflow-y-auto">
            <h2 className="text-2xl font-bold mb-4 sticky top-0 bg-white pb-4">Shipment Timeline</h2>
            
            <div className="mb-6 p-4 bg-gray-50 rounded">
              <p className="text-sm text-gray-600">Drug: <strong>{viewingTimeline.order?.drugId?.drugName}</strong></p>
              <p className="text-sm text-gray-600">Quantity: <strong>{viewingTimeline.order?.quantity}</strong></p>
            </div>

            <div className="space-y-6">
              {viewingTimeline.timeline?.map((entry, index) => (
                <div key={entry._id} className="flex gap-4">
                  <div className="flex flex-col items-center">
                    <div className="w-4 h-4 bg-blue-600 rounded-full"></div>
                    {index < viewingTimeline.timeline.length - 1 && (
                      <div className="w-1 h-12 bg-blue-200 mt-2"></div>
                    )}
                  </div>
                  <div className="pb-8">
                    <p className="font-bold text-lg">{entry.status}</p>
                    {entry.location && <p className="text-gray-600 text-sm">📍 {entry.location}</p>}
                    {entry.note && <p className="text-gray-500 text-sm italic">"{entry.note}"</p>}
                    <p className="text-gray-400 text-xs mt-2">
                      {new Date(entry.updatedAt).toLocaleString()}
                    </p>
                  </div>
                </div>
              ))}
            </div>

            <button
              onClick={() => setViewingTimeline(null)}
              className="btn-secondary w-full mt-6"
            >
              Close
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
